### ISSUE TITLE
Jobs Wrong URL

### ISSUE THREAD

**Issue by ttbek** [genepi/cloudgene#13]
When viewing a job as an admin, the "Jobs" link in the upper left is linked incorrectly to /admin.html#!pages/jobs instead of to /admin.html#!pages/admin-jobs and clicking it results in a 404.  

Edit: Version: 1.30.5 (built by travis on 2018-09-14T07:42:13Z)

**Comment by lukfor** [comment]
Fixed in > 2.0.0 RC1

**Comment by ttbek** [comment]
Awesome!  Thanks for your continuing work on this project.
