### ISSUE TITLE
Non-Admin Job Logfiles

### ISSUE THREAD

**Issue by ttbek** [genepi/cloudgene#14]
When a job fails, the message given to the user is: "Execution failed. Please have a look at the logfile for details."

Non-admin users don't seem to have access to the logfiles, so this message should probably be changed for them.  Maybe to, "Execution failed.  Please contact the server administrators for help if you believe this job should have completed successfully."  Or something along those lines.  

That, or give them access to the logfiles, but I would assume that potentially could be a security risk.  

Edit: Version: 1.30.5 (built by travis on 2018-09-14T07:42:13Z)

**Comment by lukfor** [comment]
Fixed and is available in the next release
