### ISSUE TITLE
Hard-Coded Rscript Path

### ISSUE THREAD

**Issue by jjfarrell** [genepi/cloudgene#21]
In the cloudgene 2.0.0 RC6 release, the Rscript path is hard coded to be RSCRIPT_PATH = "/usr/bin/Rscript" in src/main/java/cloudgene/mapred/plugins/rscript/RScriptBinary.java.   Could this variable be made configurable? Or check if Rscript is present on the path and use that?  For our HPCC, we use [module ](http://www.bu.edu/tech/support/research/software-and-programming/software-and-applications/modules/#Commands) to update paths to software versions. So Rscript is not found in a standard path and will vary based on the version of R loaded.

**Comment by lukfor** [comment]
Thank you, good point! We add the R Path to the `settings.yaml` file in one of the next releases.

**Comment by lukfor** [comment]
Is fixed and is available with the next release.

We use now the following strategy to find Rscript:

1. checks if it is set in `settings.yaml`:
```
plugins:
  rscript:
    home: /usr/lib/R/bin
```
2. checks if env variable `$R_HOME` ist set
3. checks if Rscript is in `$PATH`
