### ISSUE TITLE
Valid  Gruntfile could not be found

### ISSUE THREAD

**Issue by jjfarrell** [genepi/cloudgene#22]
I tried to build the Webinterface and used the following steps according to the docs:

cd src/main/html/webapp
npm install
mkdir tmp
grunt

However  the grunt command indicated a valid Gruntfile could not be found. There is not a Gruntfile in src/main/html/webapp.  Any suggestions for resolving this?

**Comment by jjfarrell** [comment]
Found the file Gruntfile.js but it was not in the master branch. It is missing from the Master branch.  Not sure this is the most updated Gruntfile.js.

**Comment by lukfor** [comment]
Thank you for pointing out the mistake! We switched from gruntjs to a custom build script (build.js). Moreover, we included the build process of the frontend into the maven file using frontend-maven-plugin. Thus, a single `mvn install` command is sufficient to build also the frontend.

I updated the instruction in https://github.com/genepi/cloudgene/blob/master/DEVELOPING.md
