### ISSUE TITLE
Cloudgene seems not to work with Yarn

### ISSUE THREAD

**Issue by KHN190** [genepi/cloudgene#5]
Hi,

I found Cloudgene depends on Jobtracker & Tasktracker. They have already been replaced by Yarn. I installed Hadoop 3.1.0 and set up as:
```
# mapred-site.xml
<configuration>
  <property>
    <name>mapreduce.framework.name</name>
    <value>yarn</value>
  </property>
</configuration>

# yarn-site.xml
<configuration>
  <property>
    <name>yarn.resourcemanager.address</name>
    <value>hdfs://localhost:8021</value>
  </property>
</configuration>
```

But in cloudgene.err it displayed:
```
Unknown rpc kind in rpc headerRPC_WRITABLE
```
, which is caused by incompatibility between MR1 with MR2 (using yarn). Is there anyway I can fix it? Or do I have to downgrade Hadoop to older version?

**Comment by lukfor** [comment]
Currently, Cloudgene works only on MR1, but we plan to update it to MR2 in the near feature. I will keep you updated!

**Comment by KHN190** [comment]
@lukfor Thanks for reply! While, can you provide prerequisition to setup MR1 on  Ubuntu 16.04?

**Comment by KHN190** [comment]
@lukfor Thanks for reply! I'll try switch to MR1 for now.
CDH5 contained both MR1 & MR2, which may be useful.

While, can you provide a developer guide? I'm working for a commercial corp and found this project useful. It'll be good if I can test & make some commits.
Best regards.

**Comment by lukfor** [comment]
Great, if you like our projects! Thanks, contributions are more than welcome!

A very first draft of a developer guide is here: https://github.com/genepi/cloudgene/blob/master/DEVELOPING.md

**Comment by KHN190** [comment]
Hi,

Sorry for the late reply, but I didn’t have time before the last weekend…

Here’s the answer:
https://stackoverflow.com/questions/25983283/how-to-load-vendor-asset-folder-in-rails-4

For short, the assets in vendor directory were not auto-loaded…
So, either require it in application.js like in the thread, or move assets/vendor/* to app/assets/javascript

The assets under app/assets/* are automatically loaded & included.

p.s. I haven’t used this gem for quite a long time…For simplicity you can just download any third-party js to /app/assets, import, then use it. No gem required.

Best regards.


在 2018年4月12日，下午5:59，Lukas Forer <notifications@github.com<mailto:notifications@github.com>> 写道：


Great, if you like our projects! Thanks, contributions are more than welcome!

A very first draft of a developer guide is here: https://github.com/genepi/cloudgene/blob/master/DEVELOPING.md
